title = "dataBar"
baseURL = "/"
languageCode = "En"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

#ignore files as recommended
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Experiences from a data scientist in training"
  facebook = ""
  twitter = "https://twitter.com/lbarcelo"
  instagram = ""
  youtube = ""
  github = "https://github.com/lbo34"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/laurentbarcelo/"
  email = "dataBarBlog@gmail.com"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/artfromdata.jpg"
  recent_posts_number = 2
